### ISSUE TITLE
Readme should include screenshot of output

### ISSUE THREAD

**Issue by ebidel** [rmurphey/chrome-http2-log-parser#2]
Would love to know what this looks like without installing it just yet :)

**Comment by rmurphey** [comment]
Good thing @paulirish opened #1 then :)

**Comment by ebidel** [comment]
Whhhaaaa. Sorry, should of checked existing issues. @paulirish strikes again.

**Comment by rmurphey** [comment]
I just assumed you were sitting next to each other :P
